default:
  tags:
    - common

stages:
  - build
  - test
  - deliver

BuildCode:
  image: python:3.10
  stage: build
  tags:
    - common
  script:
    - apt-get update -qy
    - apt install -y python3-pip
    - apt install -y python3-pygame

TestCode:
  stage: test
  tags:
    - common
  script:
    - pip install -r requirements.txt
    - PYTHONPATH=src python -m pytest --cov src tests
  artifacts:
    paths:
      - coverage.xml
  coverage: '/TOTAL\s+(\d+%)$/'
